name: Deploy app on Firebase

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: copy google-service
        env:
          GOOGLE_SERVICES_JSON: ${{secrets.GOOLE_SERVICES_JSON_DEV}}
        run: echo ${GOOGLE_SERVICES_JSON} | base64 --decode --ignore-garbage > ./app/google-services.json
      - name: Release build
        run: |
          echo ${{ secrets.ANDROID_KEYSTORE_BASE64 }} | base64 --decode > release.keystore
          export ANDROID_KEYSTORE_PASSWORD='${{ secrets.ANDROID_KEYSTORE_PASSWORD }}'
          export ANDROID_KEY_ALIAS='${{ secrets.ANDROID_KEY_ALIAS }}'
          export ANDROID_KEY_PASSWORD='${{ secrets.ANDROID_KEY_PASSWORD }}'
          ./gradlew assembleRelease
      - name: Deploy app on Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.1.1
        with:
          appId: ${{secrets.FIREBASE_DEV_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: tester
          file: app/build/outputs/apk/release/app-release.apk
