name: Deploy app on Firebase

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Debug build
      run: ./gradlew assembleDebug
    - name: Deploy app on Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.1.1
      with:
        appId: ${{secrets.FIREBASE_DEV_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: tester
        file: app/build/outputs/apk/debug/app-debug.apk
